export const WOOL_LIST_REQUEST = "WOOL_LIST_REQUEST";
export const WOOL_LIST_SUCCESS = "WOOL_LIST_SUCCESS";
export const WOOL_LIST_FAIL = "WOOL_LIST_FAIL";


export const WOOL_DETAILS_REQUEST = "WOOL_DETAILS_REQUEST";
export const WOOL_DETAILS_SUCCESS = "WOOL_DETAILS_SUCCESS";
export const WOOL_DETAILS_FAIL = "WOOL_DETAILS_FAIL";
export const WOOL_DETAILS_RESET = "WOOL_DETAILS_RESET";

export const WOOL_DELETE_REQUEST = "WOOL_DELETE_REQUEST";
export const WOOL_DELETE_SUCCESS = "WOOL_DELETE_SUCCESS";
export const WOOL_DELETE_FAIL = "WOOL_DELETE_FAIL";
export const WOOL_DELETE_RESET = "WOOL_DELETE_RESET";

export const WOOL_CREATE_REQUEST = "WOOL_CREATE_REQUEST";
export const WOOL_CREATE_SUCCESS = "WOOL_CREATE_SUCCESS";
export const WOOL_CREATE_FAIL = "WOOL_CREATE_FAIL";
export const WOOL_CREATE_RESET = "WOOL_CREATE_RESET";

export const WOOL_UPDATE_REQUEST = "WOOL_UPDATE_REQUEST";
export const WOOL_UPDATE_SUCCESS = "WOOL_UPDATE_SUCCESS";
export const WOOL_UPDATE_FAIL = "WOOL_UPDATE_FAIL";
export const WOOL_UPDATE_RESET = "WOOL_UPDATE_RESET";


export const WOOL_FILTER_REQUEST = "WOOL_FILTER_REQUEST";
export const WOOL_FILTER_SUCCESS = "WOOL_FILTER_SUCCESS";
export const WOOL_FILTER_FAIL = "WOOL_FILTER_FAIL";
export const WOOL_FILTER_RESET = "WOOL_FILTER_RESET";