export const WOOL_LIST_REQUEST = "WOOL_LIST_REQUEST";
export const WOOL_LIST_SUCCESS = "WOOL_LIST_SUCCESS";
export const WOOL_LIST_FAIL = "WOOL_LIST_FAIL";


export const WOOL_DETAILS_REQUEST = "WOOL_DETAILS_REQUEST";
export const WOOL_DETAILS_SUCCESS = "WOOL_DETAILS_SUCCESS";
export const WOOL_DETAILS_FAIL = "WOOL_DETAILS_FAIL";